export const SET_DATA = 'SET_DATA';
export const SET_ACTIVE_GROUP = 'SET_ACTIVE_GROUP';
export const SET_ACTIVE_CAMPER = 'SET_ACTIVE_CAMPER';
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const INCREMENT_NEXT_GROUP_ID = 'INCREMENT_NEXT_GROUP_ID';
export const SET_NEXT_GROUP_ID = 'SET_NEXT_GROUP_ID';